"""Common speaker protocol for AudioProSpeaker and SamsungSoundbar."""

from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class SpeakerLike(Protocol):
    enabled: bool
    state: Any

    async def start(self) -> None: ...
    async def stop(self) -> None: ...
    async def request_refresh(self) -> None: ...
    def snapshot(self) -> dict[str, Any]: ...

    async def power_on(self) -> None: ...
    async def power_off(self) -> None: ...

    async def volume_up(self) -> None: ...
    async def volume_down(self) -> None: ...
    async def set_volume(self, pct: int) -> None: ...

    async def set_muted(self, target: bool) -> None: ...
    async def mute_toggle(self) -> None: ...

    async def play(self) -> None: ...
    async def pause(self) -> None: ...
    async def stop_playback(self) -> None: ...
    async def fast_forward(self) -> None: ...
    async def rewind(self) -> None: ...

    async def set_source(self, source: str) -> None: ...
    async def preset(self, n: int) -> None: ...
    async def next_preset(self) -> None: ...
    async def previous_preset(self) -> None: ...
    async def play_url(self, url: str) -> None: ...