"""The speaker interface flows and the dispatcher rely on.

Both backends (AudioProSpeaker, SamsungSoundbar) implement these. A backend that
can't do something raises RuntimeError("unsupported_on_backend:<action>").
Backend-specific extras (Audio Pro multiroom, soundbar release_to_tv, play_url's
restream option) are called only by that backend's flows.
"""

from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class SpeakerLike(Protocol):
    enabled: bool
    state: Any
    initial: Any   # InitialStatus: the first reading after start-up

    async def start(self) -> None: ...
    async def stop(self) -> None: ...
    async def request_refresh(self) -> dict[str, Any]: ...
    def snapshot(self) -> dict[str, Any]: ...
    def listening(self) -> bool: ...   # a listen session is in progress

    async def power_off(self) -> None: ...

    async def volume_up(self) -> None: ...
    async def volume_down(self) -> None: ...
    async def set_volume(self, pct: int) -> None: ...

    async def set_muted(self, target: bool) -> None: ...
    async def mute_toggle(self) -> None: ...

    async def play(self) -> None: ...
    async def pause(self) -> None: ...
    async def play_pause(self) -> None: ...
    async def stop_playback(self) -> None: ...
    async def next_track(self) -> None: ...
    async def previous_track(self) -> None: ...

    async def set_source(self, source: str) -> None: ...
    async def preset(self, n: int) -> None: ...
    async def next_preset(self) -> None: ...
    async def previous_preset(self) -> None: ...
    async def play_url(self, url: str) -> None: ...
